distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Fri May 17 18:09:41 2019"
installation_id: "a0590abd-703c-472c-a20f-0c8e2c6e26ab"
rime_version: 1.4.0