var:
  last_build_time: 1561079153
  option:
    simplification: true
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1561046059
    luna_pinyin: 1561046036
    luna_pinyin_simp: 1558096317